### ISSUE TITLE
How to use tht function nmpc.stage_cost

### ISSUE THREAD

**Issue by 17150934** [hilo-mpc/hilo-mpc#10]
My objective function is non quadratic, so I want to use the function "nmpc.stage_cost". But I didn't find the relevant guide.
Does anyone know how to use this function?
Or does anyone know how to establish a non quadratic objective function by other methods?
![图片](https://user-images.githubusercontent.com/76049488/188418107-df67a757-605b-4a07-8fdf-7607e87abb02.png)

**Comment by brunomorampc** [comment]
Hi,

You're right. I thought I had put some examples on how to use the generic cost but i didn't apparently.

I don't have access to my PC at the moment. I'll send you an example in 2 days at latest. Thanks for your patience

**Comment by brunomorampc** [comment]
Hi @17150934,

there is snippet I got from the example [CSTR_example.ipynb](https://github.com/hilo-mpc/examples/blob/ecad3dfcda0aa96cfd1789aba656d268d5ce1b73/jupyter_notebooks/CSTR_Example.ipynb) 

```
# Model Setup
model = hybrid_model()
model.substitute_from(ann) # Substite the labels in the model with the ANN model
model.setup(dt = sampling_period)

# NMPC Hybrid Model Setup
nmpc_hybrid_model = NMPC(model)
nmpc_hybrid_model.set_scaling(x_scaling = x_scaling_value, u_scaling = u_scaling_value)
nmpc_hybrid_model.stage_cost.cost = model.x[0] / C_A_0 + model.u[0] * heat_price
...
```

so you basically have to use the states of the model, by accessing `model.x[here_the_state_index]`. The state index is the position of the corresponding state. 

You can do the same thing with the terminal cost by using `nmpc_hybrid_model.terminal_cost.cost =...`

Does that solve your problem?
Thanks for your patience :)

**Comment by 17150934** [comment]
@brunomorampc 
Thank you very much and I will try

**Comment by brunomorampc** [comment]
I'll close the issue. If the problem persists let me know and I'll open it again
