### ISSUE TITLE
Prediction and control horizon

### ISSUE THREAD

**Issue by 17150934** [hilo-mpc/hilo-mpc#11]
When I only use nmpc.horizon = 10, everything is right.
But when I want to set different control and prediction horizon, i.e. 
      `nmpc.prediction_horizon=10 //
nmpc.control_horizon=4`
 there exists an error:
`Traceback (most recent call last):

  File ~/plexe-pyapi/examples/untitled0.py:42 in <module>
    nmpc.setup(options={'print_level':0})

  File ~/anaconda3/lib/python3.8/site-packages/hilo_mpc/modules/controller/mpc.py:1615 in setup
    u_ii = u[ii, 0]

IndexError: index 4 is out of bounds for axis 0 with size 4`

What's the problem, please

**Comment by brunomorampc** [comment]
can you send me your code please?

**Comment by brunomorampc** [comment]
I found the problem, I'll fix it and release a new version
