### ISSUE TITLE
Version of numpy

### ISSUE THREAD

**Issue by zachanton** [hilo-mpc/hilo-mpc#14]
Thank you for a great project! Is it really necessary to border the numpy version numpy<=1.19.5 in setup.cfg?

**Comment by brunomorampc** [comment]
Hi zachanton,

Thanks for your comment.

At that time  the problem was that Casadi would not work with a higher version of numpy. The problem seems to be risolved for casadi 3.6. We will have a look at it and see if we can relax that constraint on the numpy version. Thanks for pointint that out!

**Comment by brunomorampc** [comment]
fixed with the recent pull request
